export type Terrain = "Flat" | "Mixed" | "Hilly";

export type Route = {
  id: string;
  name: string;
  neighborhood: string;
  city: string;
  distanceKm: number;
  durationMin: number;
  terrain: Terrain;
  elevationGainM: number;
  mtaStation: string;
  mtaLines: string;
  finishSpot: string;
  finishType: string;
  landmarks: string[];
  note: string;
};

export const routes: Route[] = [
  {
    id: "1",
    name: "Brooklyn Bridge & DUMBO",
    neighborhood: "DUMBO",
    city: "New York",
    distanceKm: 8.2,
    durationMin: 48,
    terrain: "Mixed",
    elevationGainM: 42,
    mtaStation: "High St–Brooklyn Bridge",
    mtaLines: "A · C",
    finishSpot: "Shake Shack",
    finishType: "burgers & shakes",
    landmarks: ["Brooklyn Bridge", "DUMBO Archway", "Brooklyn Bridge Park"],
    note: "Selfie sticks at dawn. You've been warned.",
  },
  {
    id: "2",
    name: "Central Park Loop",
    neighborhood: "Upper West Side",
    city: "New York",
    distanceKm: 10.0,
    durationMin: 58,
    terrain: "Mixed",
    elevationGainM: 67,
    mtaStation: "59 St–Columbus Circle",
    mtaLines: "A · B · C · D · 1",
    finishSpot: "Gregorys Coffee",
    finishType: "coffee & breakfast sandwich",
    landmarks: ["Columbus Circle", "Bethesda Terrace", "The Mall", "Sheep Meadow"],
    note: "Horse shit, pedicabs, tourists on Citibikes. Classic.",
  },
  {
    id: "3",
    name: "Williamsburg Waterfront",
    neighborhood: "Williamsburg",
    city: "New York",
    distanceKm: 7.4,
    durationMin: 44,
    terrain: "Flat",
    elevationGainM: 18,
    mtaStation: "Bedford Av",
    mtaLines: "L",
    finishSpot: "Devocion",
    finishType: "coffee & pastries",
    landmarks: ["Domino Park", "East River State Park", "Williamsburg Bridge"],
    note: "Flat, breezy, and full of people who definitely didn't run here.",
  },
  {
    id: "4",
    name: "East River Greenway",
    neighborhood: "Lower East Side",
    city: "New York",
    distanceKm: 6.1,
    durationMin: 36,
    terrain: "Flat",
    elevationGainM: 8,
    mtaStation: "Delancey St–Essex St",
    mtaLines: "F · J · M · Z",
    finishSpot: "Russ & Daughters Cafe",
    finishType: "bagels & lox",
    landmarks: ["Williamsburg Bridge", "East River Park", "Pier 35"],
    note: "The one LES route where you won't get stuck behind a brunch line. Almost.",
  },
  {
    id: "5",
    name: "Hudson River Park",
    neighborhood: "West Village",
    city: "New York",
    distanceKm: 9.3,
    durationMin: 54,
    terrain: "Flat",
    elevationGainM: 14,
    mtaStation: "14 St",
    mtaLines: "A · C · E · L",
    finishSpot: "Jack's Wife Freda",
    finishType: "brunch & coffee",
    landmarks: ["Hudson River Park", "Pier 45", "Little Island"],
    note: "Watch for cyclists who think the bike lane is a personality test.",
  },
  {
    id: "6",
    name: "Prospect Park Perimeter",
    neighborhood: "Park Slope",
    city: "New York",
    distanceKm: 11.5,
    durationMin: 68,
    terrain: "Mixed",
    elevationGainM: 52,
    mtaStation: "Grand Army Plaza",
    mtaLines: "2 · 3",
    finishSpot: "Southside Coffee",
    finishType: "coffee & pastries",
    landmarks: ["Grand Army Plaza", "Audubon Center", "Prospect Park Lake"],
    note: "Central Park's slightly less insufferable sibling. Slightly.",
  },
  {
    id: "7",
    name: "Queensboro Bridge",
    neighborhood: "Long Island City",
    city: "New York",
    distanceKm: 12.8,
    durationMin: 76,
    terrain: "Mixed",
    elevationGainM: 88,
    mtaStation: "Queensboro Plaza",
    mtaLines: "7 · N · W",
    finishSpot: "Sweetleaf Coffee",
    finishType: "coffee & light bites",
    landmarks: ["Queensboro Bridge", "Roosevelt Island Tram", "Gantry Plaza State Park"],
    note: "The views are great. The incline is not a negotiable opinion.",
  },
  {
    id: "8",
    name: "Harlem River Drive",
    neighborhood: "Harlem",
    city: "New York",
    distanceKm: 14.2,
    durationMin: 84,
    terrain: "Hilly",
    elevationGainM: 95,
    mtaStation: "125 St",
    mtaLines: "4 · 5 · 6",
    finishSpot: "Sylvia's Restaurant",
    finishType: "southern breakfast",
    landmarks: ["Marcus Garvey Park", "Harlem River Greenway", "Washington Bridge"],
    note: "Actual hills. Actual sweat. Sylvia's doesn't care how you got there.",
  },
  {
    id: "9",
    name: "Roosevelt Island Loop",
    neighborhood: "Roosevelt Island",
    city: "New York",
    distanceKm: 5.6,
    durationMin: 33,
    terrain: "Flat",
    elevationGainM: 22,
    mtaStation: "Roosevelt Island",
    mtaLines: "F",
    finishSpot: "Piccolo Trattoria",
    finishType: "espresso & pastries",
    landmarks: ["Four Freedoms Park", "Blackwell Island Lighthouse", "Cornell Tech"],
    note: "The tram is right there. You chose running anyway. Respect?",
  },
  {
    id: "10",
    name: "Coney Island Boardwalk",
    neighborhood: "Coney Island",
    city: "New York",
    distanceKm: 16.4,
    durationMin: 98,
    terrain: "Flat",
    elevationGainM: 12,
    mtaStation: "Coney Island–Stillwell Av",
    mtaLines: "D · F · N · Q",
    finishSpot: "Tom's Restaurant",
    finishType: "diner breakfast",
    landmarks: ["Coney Island Boardwalk", "New York Aquarium", "Wonder Wheel"],
    note: "16K for a diner breakfast. You're not well, but you're consistent.",
  },
];
