export type Terrain = "Flat" | "Mixed" | "Hilly";

export type Route = {
  id: string;
  name: string;
  neighborhood: string;
  city: string;
  distanceKm: number;
  durationMin: number;
  terrain: Terrain;
  elevationGainM: number;
  mtaStation: string;
  mtaLines: string;
  finishSpot: string;
  finishType: string;
};

export const routes: Route[] = [
  {
    id: "1",
    name: "Brooklyn Bridge & DUMBO",
    neighborhood: "DUMBO",
    city: "New York",
    distanceKm: 8.2,
    durationMin: 48,
    terrain: "Mixed",
    elevationGainM: 42,
    mtaStation: "High St–Brooklyn Bridge",
    mtaLines: "A · C",
    finishSpot: "Shake Shack",
    finishType: "burgers & shakes",
  },
  {
    id: "2",
    name: "Central Park Loop",
    neighborhood: "Upper West Side",
    city: "New York",
    distanceKm: 10.0,
    durationMin: 58,
    terrain: "Mixed",
    elevationGainM: 67,
    mtaStation: "59 St–Columbus Circle",
    mtaLines: "A · B · C · D · 1",
    finishSpot: "Gregorys Coffee",
    finishType: "coffee & breakfast sandwich",
  },
  {
    id: "3",
    name: "Williamsburg Waterfront",
    neighborhood: "Williamsburg",
    city: "New York",
    distanceKm: 7.4,
    durationMin: 44,
    terrain: "Flat",
    elevationGainM: 18,
    mtaStation: "Bedford Av",
    mtaLines: "L",
    finishSpot: "Devocion",
    finishType: "coffee & pastries",
  },
  {
    id: "4",
    name: "East River Greenway",
    neighborhood: "Lower East Side",
    city: "New York",
    distanceKm: 6.1,
    durationMin: 36,
    terrain: "Flat",
    elevationGainM: 8,
    mtaStation: "Delancey St–Essex St",
    mtaLines: "F · J · M · Z",
    finishSpot: "Russ & Daughters Cafe",
    finishType: "bagels & lox",
  },
  {
    id: "5",
    name: "Hudson River Park",
    neighborhood: "West Village",
    city: "New York",
    distanceKm: 9.3,
    durationMin: 54,
    terrain: "Flat",
    elevationGainM: 14,
    mtaStation: "14 St",
    mtaLines: "A · C · E · L",
    finishSpot: "Jack's Wife Freda",
    finishType: "brunch & coffee",
  },
  {
    id: "6",
    name: "Prospect Park Perimeter",
    neighborhood: "Park Slope",
    city: "New York",
    distanceKm: 11.5,
    durationMin: 68,
    terrain: "Mixed",
    elevationGainM: 52,
    mtaStation: "Grand Army Plaza",
    mtaLines: "2 · 3",
    finishSpot: "Southside Coffee",
    finishType: "coffee & pastries",
  },
  {
    id: "7",
    name: "Queensboro Bridge",
    neighborhood: "Long Island City",
    city: "New York",
    distanceKm: 12.8,
    durationMin: 76,
    terrain: "Mixed",
    elevationGainM: 88,
    mtaStation: "Queensboro Plaza",
    mtaLines: "7 · N · W",
    finishSpot: "Sweetleaf Coffee",
    finishType: "coffee & light bites",
  },
  {
    id: "8",
    name: "Harlem River Drive",
    neighborhood: "Harlem",
    city: "New York",
    distanceKm: 14.2,
    durationMin: 84,
    terrain: "Hilly",
    elevationGainM: 95,
    mtaStation: "125 St",
    mtaLines: "4 · 5 · 6",
    finishSpot: "Sylvia's Restaurant",
    finishType: "southern breakfast",
  },
  {
    id: "9",
    name: "Roosevelt Island Loop",
    neighborhood: "Roosevelt Island",
    city: "New York",
    distanceKm: 5.6,
    durationMin: 33,
    terrain: "Flat",
    elevationGainM: 22,
    mtaStation: "Roosevelt Island",
    mtaLines: "F",
    finishSpot: "Piccolo Trattoria",
    finishType: "espresso & pastries",
  },
  {
    id: "10",
    name: "Coney Island Boardwalk",
    neighborhood: "Coney Island",
    city: "New York",
    distanceKm: 16.4,
    durationMin: 98,
    terrain: "Flat",
    elevationGainM: 12,
    mtaStation: "Coney Island–Stillwell Av",
    mtaLines: "D · F · N · Q",
    finishSpot: "Tom's Restaurant",
    finishType: "diner breakfast",
  },
];
