export type Terrain = "Flat" | "Mixed" | "Hilly";
export type TechnicalDifficulty = "Low" | "Medium" | "High";
export type ImpactLevel = "Low" | "Moderate" | "High";
export type RouteStatus = "Active" | "Caution" | "Restricted";

export type Route = {
  id: string;
  routeId: string;
  name: string;
  city: string;
  distanceKm: number;
  durationMin: number;
  avgPaceMinPerKm: number;
  terrain: Terrain;
  elevationGainM: number;
  technicalDifficulty: TechnicalDifficulty;
  startHub: string;
  startLine: string;
  startCoords: string;
  endLocation: string;
  endCoords: string;
  endTransitHub: string;
  endTransitLine: string;
  weatherImpact: ImpactLevel;
  constructionAlert: string | null;
  status: RouteStatus;
};

export const routes: Route[] = [
  {
    id: "1",
    routeId: "NYC-082",
    name: "Brooklyn Bridge Corridor",
    city: "New York",
    distanceKm: 8.2,
    durationMin: 48,
    avgPaceMinPerKm: 5.9,
    terrain: "Mixed",
    elevationGainM: 42,
    technicalDifficulty: "Medium",
    startHub: "High St–Brooklyn Bridge",
    startLine: "A / C",
    startCoords: "40.6993, -73.9903",
    endLocation: "DUMBO Waterfront Terminal",
    endCoords: "40.7033, -73.9881",
    endTransitHub: "York St",
    endTransitLine: "F",
    weatherImpact: "Moderate",
    constructionAlert: "Lane reduction on Adams St (until Q3)",
    status: "Caution",
  },
  {
    id: "2",
    routeId: "SFO-054",
    name: "Embarcadero North Segment",
    city: "San Francisco",
    distanceKm: 5.4,
    durationMin: 32,
    avgPaceMinPerKm: 5.9,
    terrain: "Flat",
    elevationGainM: 12,
    technicalDifficulty: "Low",
    startHub: "Embarcadero Station",
    startLine: "BART",
    startCoords: "37.7928, -122.3968",
    endLocation: "Pier 39 Transit Loop",
    endCoords: "37.8087, -122.4098",
    endTransitHub: "Jefferson & Taylor",
    endTransitLine: "F Market",
    weatherImpact: "High",
    constructionAlert: null,
    status: "Active",
  },
  {
    id: "3",
    routeId: "LON-121",
    name: "Thames South Bank Loop",
    city: "London",
    distanceKm: 12.1,
    durationMin: 72,
    avgPaceMinPerKm: 6.0,
    terrain: "Mixed",
    elevationGainM: 58,
    technicalDifficulty: "Medium",
    startHub: "London Bridge",
    startLine: "Jubilee / Northern",
    startCoords: "51.5051, -0.0864",
    endLocation: "Borough High St Junction",
    endCoords: "51.5036, -0.0897",
    endTransitHub: "London Bridge",
    endTransitLine: "Jubilee / Northern",
    weatherImpact: "Moderate",
    constructionAlert: "Thames Path diversion near HMS Belfast",
    status: "Caution",
  },
  {
    id: "4",
    routeId: "TYO-156",
    name: "Shibuya–Yoyogi Axis",
    city: "Tokyo",
    distanceKm: 15.6,
    durationMin: 95,
    avgPaceMinPerKm: 6.1,
    terrain: "Hilly",
    elevationGainM: 124,
    technicalDifficulty: "High",
    startHub: "Shibuya Station",
    startLine: "JR Yamanote",
    startCoords: "35.6580, 139.7016",
    endLocation: "Yoyogi Park South Gate",
    endCoords: "35.6717, 139.6949",
    endTransitHub: "Yoyogi-Koen",
    endTransitLine: "Chiyoda",
    weatherImpact: "Low",
    constructionAlert: null,
    status: "Active",
  },
  {
    id: "5",
    routeId: "CHI-198",
    name: "Lakefront North Long",
    city: "Chicago",
    distanceKm: 19.8,
    durationMin: 118,
    avgPaceMinPerKm: 6.0,
    terrain: "Flat",
    elevationGainM: 28,
    technicalDifficulty: "Low",
    startHub: "Grand Red Line",
    startLine: "CTA Red",
    startCoords: "41.8918, -87.6281",
    endLocation: "Montrose Harbor Access",
    endCoords: "41.9662, -87.6378",
    endTransitHub: "Wilson",
    endTransitLine: "CTA Red / Purple",
    weatherImpact: "High",
    constructionAlert: "Lakefront Trail repair mile 4.2–4.8",
    status: "Caution",
  },
  {
    id: "6",
    routeId: "PAR-073",
    name: "Canal Saint-Martin Circuit",
    city: "Paris",
    distanceKm: 7.3,
    durationMin: 44,
    avgPaceMinPerKm: 6.0,
    terrain: "Flat",
    elevationGainM: 18,
    technicalDifficulty: "Low",
    startHub: "République",
    startLine: "Métro 3 / 5 / 8",
    startCoords: "48.8676, 2.3631",
    endLocation: "Jaurès Interchange",
    endCoords: "48.8822, 2.3704",
    endTransitHub: "Jaurès",
    endTransitLine: "Métro 2 / 5 / 7bis",
    weatherImpact: "Low",
    constructionAlert: null,
    status: "Active",
  },
  {
    id: "7",
    routeId: "NYC-105",
    name: "Central Park Perimeter",
    city: "New York",
    distanceKm: 10.0,
    durationMin: 58,
    avgPaceMinPerKm: 5.8,
    terrain: "Mixed",
    elevationGainM: 67,
    technicalDifficulty: "Medium",
    startHub: "59 St–Columbus Circle",
    startLine: "A / B / C / D / 1",
    startCoords: "40.7681, -73.9819",
    endLocation: "Grand Army Plaza",
    endCoords: "40.7648, -73.9730",
    endTransitHub: "5 Av / 59 St",
    endTransitLine: "N / R / W",
    weatherImpact: "Moderate",
    constructionAlert: null,
    status: "Active",
  },
  {
    id: "8",
    routeId: "BER-089",
    name: "Tiergarten West Loop",
    city: "Berlin",
    distanceKm: 8.9,
    durationMin: 52,
    avgPaceMinPerKm: 5.8,
    terrain: "Flat",
    elevationGainM: 22,
    technicalDifficulty: "Low",
    startHub: "Hauptbahnhof",
    startLine: "S-Bahn / U-Bahn",
    startCoords: "52.5250, 13.3694",
    endLocation: "Großer Stern",
    endCoords: "52.5145, 13.3489",
    endTransitHub: "Tiergarten",
    endTransitLine: "S-Bahn S5 / S7",
    weatherImpact: "Low",
    constructionAlert: "Path closure Ebertstr (weekends)",
    status: "Caution",
  },
  {
    id: "9",
    routeId: "SFO-112",
    name: "Golden Gate Approach",
    city: "San Francisco",
    distanceKm: 11.2,
    durationMin: 68,
    avgPaceMinPerKm: 6.1,
    terrain: "Hilly",
    elevationGainM: 156,
    technicalDifficulty: "High",
    startHub: "Civic Center",
    startLine: "BART",
    startCoords: "37.7795, -122.4138",
    endLocation: "Golden Gate Welcome Center",
    endCoords: "37.8078, -122.4750",
    endTransitHub: "Golden Gate Bridge Plaza",
    endTransitLine: "Muni 28",
    weatherImpact: "High",
    constructionAlert: null,
    status: "Active",
  },
  {
    id: "10",
    routeId: "LON-067",
    name: "Regent's Canal East",
    city: "London",
    distanceKm: 6.7,
    durationMin: 40,
    avgPaceMinPerKm: 6.0,
    terrain: "Flat",
    elevationGainM: 9,
    technicalDifficulty: "Low",
    startHub: "King's Cross St Pancras",
    startLine: "Northern / Piccadilly / Victoria",
    startCoords: "51.5308, -0.1238",
    endLocation: "Victoria Park South Gate",
    endCoords: "51.5352, -0.0396",
    endTransitHub: "Mile End",
    endTransitLine: "Central / District / Hammersmith",
    weatherImpact: "Moderate",
    constructionAlert: null,
    status: "Active",
  },
  {
    id: "11",
    routeId: "CHI-142",
    name: "Riverwalk South Connector",
    city: "Chicago",
    distanceKm: 14.2,
    durationMin: 86,
    avgPaceMinPerKm: 6.1,
    terrain: "Flat",
    elevationGainM: 15,
    technicalDifficulty: "Low",
    startHub: "Roosevelt Red Line",
    startLine: "CTA Red / Orange / Green",
    startCoords: "41.8674, -87.6270",
    endLocation: "Chinatown Gateway",
    endCoords: "41.8510, -87.6337",
    endTransitHub: "Cermak-Chinatown",
    endTransitLine: "CTA Red",
    weatherImpact: "Moderate",
    constructionAlert: "Riverwalk section closed 22:00–05:00",
    status: "Caution",
  },
  {
    id: "12",
    routeId: "TYO-098",
    name: "Imperial Palace Outer Ring",
    city: "Tokyo",
    distanceKm: 9.8,
    durationMin: 58,
    avgPaceMinPerKm: 5.9,
    terrain: "Flat",
    elevationGainM: 14,
    technicalDifficulty: "Low",
    startHub: "Tokyo Station",
    startLine: "JR Yamanote / Marunouchi",
    startCoords: "35.6812, 139.7671",
    endLocation: "Sakuradamon Intersection",
    endCoords: "35.6906, 139.7532",
    endTransitHub: "Nagatacho",
    endTransitLine: "Hanzomon / Namboku / Yurakucho",
    weatherImpact: "Low",
    constructionAlert: null,
    status: "Active",
  },
];
